modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "playit_companion"
version = "${version}"
displayName = "Playit Companion"
credits = "skyevg"
authors = "skyevg"
description = '''
PRIVATE BETA - The new Playit Plugin
'''

[[mixins]]
config = "playit-companion.mixins.json"

[[dependencies.playit_companion]]
modId = "neoforge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.playit_companion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"