modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "playit_companion"
version = "${version}"
displayName = "Playit Companion"
credits = "skyevg"
authors = "skyevg"
description = '''
PRIVATE BETA - The new Playit Plugin
'''

[[dependencies.playit_companion]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.playit_companion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.21)"
ordering = "NONE"
side = "BOTH"